name: Release scrap

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v5
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run spider
        run: |
          #scrapy crawl hodyna-melomana
          touch test1.rss
          touch test2.rss
      - name: Release RSS feeds
        uses: softprops/action-gh-release@v2
        if: github.ref_type == 'tag'
        with:
          make_latest: true
          files: |
            *.rss
